-- Auto-generated subcategory seed SQL
SET session_replication_role = 'replica'; -- bypass RLS for this session

-- Children of: vehicles
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Cars', 'cars', 'vehicles/cars', 1, '99e7fdfd-463a-46f8-8651-af8d5cf883e1', '🚗', true, 2, 1000, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('SUVs & Crossovers', 'suvs', 'vehicles/suvs', 1, '99e7fdfd-463a-46f8-8651-af8d5cf883e1', '🚙', true, 2, 1001, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Motorcycles', 'motorcycles', 'vehicles/motorcycles', 1, '99e7fdfd-463a-46f8-8651-af8d5cf883e1', '🏍️', true, 2, 1002, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Pickups & Trucks', 'pickups', 'vehicles/pickups', 1, '99e7fdfd-463a-46f8-8651-af8d5cf883e1', '🛻', true, 2, 1003, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Vans & Minivans', 'vans', 'vehicles/vans', 1, '99e7fdfd-463a-46f8-8651-af8d5cf883e1', '🚐', true, 2, 1004, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Buses', 'buses', 'vehicles/buses', 1, '99e7fdfd-463a-46f8-8651-af8d5cf883e1', '🚌', true, 2, 1005, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Tuk Tuks & 3-Wheelers', 'tuk-tuks', 'vehicles/tuk-tuks', 1, '99e7fdfd-463a-46f8-8651-af8d5cf883e1', '🛺', true, 2, 1006, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Electric Vehicles', 'electric-vehicles', 'vehicles/electric-vehicles', 1, '99e7fdfd-463a-46f8-8651-af8d5cf883e1', '⚡', true, 2, 1007, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Trailers', 'trailers', 'vehicles/trailers', 1, '99e7fdfd-463a-46f8-8651-af8d5cf883e1', '🚛', true, 2, 1008, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Construction Equipment', 'construction-equipment', 'vehicles/construction-equipment', 1, '99e7fdfd-463a-46f8-8651-af8d5cf883e1', '🏗️', true, 2, 1009, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Agricultural Equipment', 'agricultural-equipment', 'vehicles/agricultural-equipment', 1, '99e7fdfd-463a-46f8-8651-af8d5cf883e1', '🚜', true, 2, 1010, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;

-- Children of: property
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Houses for Sale', 'houses-sale', 'property/houses-sale', 1, '593b5ab1-9255-49f4-99da-bce9f4399e12', '🏡', true, 2, 2000, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Houses for Rent', 'houses-rent', 'property/houses-rent', 1, '593b5ab1-9255-49f4-99da-bce9f4399e12', '🏠', true, 2, 2001, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Apartments for Sale', 'apartments-sale', 'property/apartments-sale', 1, '593b5ab1-9255-49f4-99da-bce9f4399e12', '🏢', true, 2, 2002, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Apartments for Rent', 'apartments-rent', 'property/apartments-rent', 1, '593b5ab1-9255-49f4-99da-bce9f4399e12', '🏨', true, 2, 2003, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Land & Plots', 'land-plots', 'property/land-plots', 1, '593b5ab1-9255-49f4-99da-bce9f4399e12', '📐', true, 2, 2004, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Commercial Property', 'commercial-property', 'property/commercial-property', 1, '593b5ab1-9255-49f4-99da-bce9f4399e12', '🏬', true, 2, 2005, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Short Stays & Airbnb', 'short-stays', 'property/short-stays', 1, '593b5ab1-9255-49f4-99da-bce9f4399e12', '🛏️', true, 2, 2006, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Student Hostels', 'student-hostels', 'property/student-hostels', 1, '593b5ab1-9255-49f4-99da-bce9f4399e12', '🏫', true, 2, 2007, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;

-- Children of: phones-tablets
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Smartphones', 'smartphones', 'phones-tablets/smartphones', 1, '553713d5-f796-426c-b4f1-c150724a2ed2', '📱', true, 2, 3000, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Tablets', 'tablets', 'phones-tablets/tablets', 1, '553713d5-f796-426c-b4f1-c150724a2ed2', '📲', true, 2, 3001, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Feature Phones', 'feature-phones', 'phones-tablets/feature-phones', 1, '553713d5-f796-426c-b4f1-c150724a2ed2', '📞', true, 2, 3002, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Smartwatches & Wearables', 'wearables', 'phones-tablets/wearables', 1, '553713d5-f796-426c-b4f1-c150724a2ed2', '⌚', true, 2, 3003, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Phone Accessories', 'phone-accessories', 'phones-tablets/phone-accessories', 1, '553713d5-f796-426c-b4f1-c150724a2ed2', '🔌', true, 2, 3004, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;

-- Children of: electronics
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Televisions', 'televisions', 'electronics/televisions', 1, 'ee27b33f-6498-4276-856e-6d9cb71df39a', '📺', true, 2, 4000, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Laptops & Computers', 'laptops-computers', 'electronics/laptops-computers', 1, 'ee27b33f-6498-4276-856e-6d9cb71df39a', '💻', true, 2, 4001, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Audio & Music', 'audio-music', 'electronics/audio-music', 1, 'ee27b33f-6498-4276-856e-6d9cb71df39a', '🔊', true, 2, 4002, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Cameras & Photography', 'cameras', 'electronics/cameras', 1, 'ee27b33f-6498-4276-856e-6d9cb71df39a', '📷', true, 2, 4003, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Gaming', 'gaming', 'electronics/gaming', 1, 'ee27b33f-6498-4276-856e-6d9cb71df39a', '🎮', true, 2, 4004, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Printers & Office', 'printers-office', 'electronics/printers-office', 1, 'ee27b33f-6498-4276-856e-6d9cb71df39a', '🖨️', true, 2, 4005, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Networking & IT', 'networking', 'electronics/networking', 1, 'ee27b33f-6498-4276-856e-6d9cb71df39a', '🌐', true, 2, 4006, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Home Appliances', 'home-appliances', 'electronics/home-appliances', 1, 'ee27b33f-6498-4276-856e-6d9cb71df39a', '🫙', true, 2, 4007, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Solar & Power', 'solar-power', 'electronics/solar-power', 1, 'ee27b33f-6498-4276-856e-6d9cb71df39a', '☀️', true, 2, 4008, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;

-- Children of: home-living
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Furniture', 'furniture', 'home-living/furniture', 1, 'cb644fd3-ec8d-4e47-9afc-418c8f33589c', '🪑', true, 2, 5000, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Kitchen & Dining', 'kitchen-dining', 'home-living/kitchen-dining', 1, 'cb644fd3-ec8d-4e47-9afc-418c8f33589c', '🍽️', true, 2, 5001, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Bedding & Bath', 'bedding-bath', 'home-living/bedding-bath', 1, 'cb644fd3-ec8d-4e47-9afc-418c8f33589c', '🛁', true, 2, 5002, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Garden & Outdoor', 'garden-outdoor', 'home-living/garden-outdoor', 1, 'cb644fd3-ec8d-4e47-9afc-418c8f33589c', '🌿', true, 2, 5003, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Tools & Hardware', 'tools-hardware', 'home-living/tools-hardware', 1, 'cb644fd3-ec8d-4e47-9afc-418c8f33589c', '🔨', true, 2, 5004, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Decor & Art', 'decor-art', 'home-living/decor-art', 1, 'cb644fd3-ec8d-4e47-9afc-418c8f33589c', '🖼️', true, 2, 5005, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Cleaning & Laundry', 'cleaning-laundry', 'home-living/cleaning-laundry', 1, 'cb644fd3-ec8d-4e47-9afc-418c8f33589c', '🧹', true, 2, 5006, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;

-- Children of: fashion
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Men''s Clothing', 'mens-clothing', 'fashion/mens-clothing', 1, '32042d9c-be15-47e2-9fb4-6e2a345ef4f7', '👔', true, 2, 6000, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Women''s Clothing', 'womens-clothing', 'fashion/womens-clothing', 1, '32042d9c-be15-47e2-9fb4-6e2a345ef4f7', '👗', true, 2, 6001, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Kids Clothing', 'kids-clothing', 'fashion/kids-clothing', 1, '32042d9c-be15-47e2-9fb4-6e2a345ef4f7', '👕', true, 2, 6002, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Shoes & Footwear', 'shoes', 'fashion/shoes', 1, '32042d9c-be15-47e2-9fb4-6e2a345ef4f7', '👟', true, 2, 6003, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Bags & Luggage', 'bags-luggage', 'fashion/bags-luggage', 1, '32042d9c-be15-47e2-9fb4-6e2a345ef4f7', '👜', true, 2, 6004, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Watches & Jewellery', 'watches-jewellery', 'fashion/watches-jewellery', 1, '32042d9c-be15-47e2-9fb4-6e2a345ef4f7', '💍', true, 2, 6005, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Sunglasses & Eyewear', 'eyewear', 'fashion/eyewear', 1, '32042d9c-be15-47e2-9fb4-6e2a345ef4f7', '🕶️', true, 2, 6006, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;

-- Children of: beauty
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Skincare', 'skincare', 'beauty/skincare', 1, '6f061057-bb5a-4133-a98e-2f45499583cd', '🧴', true, 2, 7000, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Hair Care', 'hair-care', 'beauty/hair-care', 1, '6f061057-bb5a-4133-a98e-2f45499583cd', '💇', true, 2, 7001, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Makeup & Cosmetics', 'makeup', 'beauty/makeup', 1, '6f061057-bb5a-4133-a98e-2f45499583cd', '💄', true, 2, 7002, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Fragrances & Perfumes', 'fragrances', 'beauty/fragrances', 1, '6f061057-bb5a-4133-a98e-2f45499583cd', '🌸', true, 2, 7003, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Vitamins & Supplements', 'supplements', 'beauty/supplements', 1, '6f061057-bb5a-4133-a98e-2f45499583cd', '💊', true, 2, 7004, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Medical Equipment', 'medical-equipment', 'beauty/medical-equipment', 1, '6f061057-bb5a-4133-a98e-2f45499583cd', '🩺', true, 2, 7005, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;

-- Children of: services
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Cleaning Services', 'cleaning-services', 'services/cleaning-services', 1, '69ad12b6-c133-4d9c-ad58-cadc8486ee12', '🧽', true, 2, 8000, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Tutoring & Education', 'tutoring', 'services/tutoring', 1, '69ad12b6-c133-4d9c-ad58-cadc8486ee12', '📚', true, 2, 8001, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Event Planning', 'event-planning', 'services/event-planning', 1, '69ad12b6-c133-4d9c-ad58-cadc8486ee12', '🎉', true, 2, 8002, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Photography & Video', 'photography-video', 'services/photography-video', 1, '69ad12b6-c133-4d9c-ad58-cadc8486ee12', '🎥', true, 2, 8003, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('IT & Tech Support', 'it-support', 'services/it-support', 1, '69ad12b6-c133-4d9c-ad58-cadc8486ee12', '🖥️', true, 2, 8004, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Legal & Financial', 'legal-financial', 'services/legal-financial', 1, '69ad12b6-c133-4d9c-ad58-cadc8486ee12', '⚖️', true, 2, 8005, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Transport & Logistics', 'transport-logistics', 'services/transport-logistics', 1, '69ad12b6-c133-4d9c-ad58-cadc8486ee12', '🚚', true, 2, 8006, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Health & Wellness', 'health-wellness', 'services/health-wellness', 1, '69ad12b6-c133-4d9c-ad58-cadc8486ee12', '🏥', true, 2, 8007, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;

-- Children of: repair-construction
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Plumbing', 'plumbing', 'repair-construction/plumbing', 1, '2af4dbd6-dcd8-429e-9f70-0db59f97d7f7', '🚿', true, 2, 9000, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Electrical', 'electrical', 'repair-construction/electrical', 1, '2af4dbd6-dcd8-429e-9f70-0db59f97d7f7', '💡', true, 2, 9001, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Roofing & Waterproofing', 'roofing', 'repair-construction/roofing', 1, '2af4dbd6-dcd8-429e-9f70-0db59f97d7f7', '🏗️', true, 2, 9002, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Painting & Decorating', 'painting-decorating', 'repair-construction/painting-decorating', 1, '2af4dbd6-dcd8-429e-9f70-0db59f97d7f7', '🎨', true, 2, 9003, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Masonry & Tiling', 'masonry-tiling', 'repair-construction/masonry-tiling', 1, '2af4dbd6-dcd8-429e-9f70-0db59f97d7f7', '🧱', true, 2, 9004, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Carpentry & Joinery', 'carpentry', 'repair-construction/carpentry', 1, '2af4dbd6-dcd8-429e-9f70-0db59f97d7f7', '🪵', true, 2, 9005, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('HVAC & AC Services', 'hvac', 'repair-construction/hvac', 1, '2af4dbd6-dcd8-429e-9f70-0db59f97d7f7', '❄️', true, 2, 9006, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;

-- Children of: commercial-equipment
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Industrial Machinery', 'industrial-machinery', 'commercial-equipment/industrial-machinery', 1, 'cdaf1b59-3677-4b3d-86c7-c391a6da1187', '⚙️', true, 2, 10000, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Restaurant & Catering', 'restaurant-catering', 'commercial-equipment/restaurant-catering', 1, 'cdaf1b59-3677-4b3d-86c7-c391a6da1187', '🍳', true, 2, 10001, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Office Furniture & Equipment', 'office-equipment', 'commercial-equipment/office-equipment', 1, 'cdaf1b59-3677-4b3d-86c7-c391a6da1187', '🗂️', true, 2, 10002, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Medical & Lab Equipment', 'medical-lab', 'commercial-equipment/medical-lab', 1, 'cdaf1b59-3677-4b3d-86c7-c391a6da1187', '🧪', true, 2, 10003, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Retail & POS Systems', 'retail-pos', 'commercial-equipment/retail-pos', 1, 'cdaf1b59-3677-4b3d-86c7-c391a6da1187', '🏪', true, 2, 10004, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Cold Room & Refrigeration', 'cold-room', 'commercial-equipment/cold-room', 1, 'cdaf1b59-3677-4b3d-86c7-c391a6da1187', '🧊', true, 2, 10005, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;

-- Children of: commercial-vehicles
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Heavy Trucks', 'heavy-trucks', 'commercial-vehicles/heavy-trucks', 1, '793b5298-cbb1-4f13-b385-7b9dc8a12900', '🚛', true, 2, 11000, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Light Commercial Vans', 'light-vans', 'commercial-vehicles/light-vans', 1, '793b5298-cbb1-4f13-b385-7b9dc8a12900', '🚐', true, 2, 11001, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Minibuses & Matatus', 'minibuses', 'commercial-vehicles/minibuses', 1, '793b5298-cbb1-4f13-b385-7b9dc8a12900', '🚌', true, 2, 11002, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Tankers & Tippers', 'tankers-tippers', 'commercial-vehicles/tankers-tippers', 1, '793b5298-cbb1-4f13-b385-7b9dc8a12900', '🪣', true, 2, 11003, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Tractor Units', 'tractor-units', 'commercial-vehicles/tractor-units', 1, '793b5298-cbb1-4f13-b385-7b9dc8a12900', '🚜', true, 2, 11004, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;

-- Children of: leisure
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Sports Equipment', 'sports-equipment', 'leisure/sports-equipment', 1, 'fbcdd6fe-075d-41df-abbc-bd352293f65d', '⚽', true, 2, 12000, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Gym & Fitness', 'gym-fitness', 'leisure/gym-fitness', 1, 'fbcdd6fe-075d-41df-abbc-bd352293f65d', '🏋️', true, 2, 12001, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Musical Instruments', 'musical-instruments', 'leisure/musical-instruments', 1, 'fbcdd6fe-075d-41df-abbc-bd352293f65d', '🎸', true, 2, 12002, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Books & Magazines', 'books', 'leisure/books', 1, 'fbcdd6fe-075d-41df-abbc-bd352293f65d', '📖', true, 2, 12003, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Bicycles', 'bicycles', 'leisure/bicycles', 1, 'fbcdd6fe-075d-41df-abbc-bd352293f65d', '🚲', true, 2, 12004, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Outdoor & Camping', 'outdoor-camping', 'leisure/outdoor-camping', 1, 'fbcdd6fe-075d-41df-abbc-bd352293f65d', '⛺', true, 2, 12005, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Board Games & Toys', 'board-games', 'leisure/board-games', 1, 'fbcdd6fe-075d-41df-abbc-bd352293f65d', '🎲', true, 2, 12006, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Arts & Crafts', 'arts-crafts', 'leisure/arts-crafts', 1, 'fbcdd6fe-075d-41df-abbc-bd352293f65d', '✂️', true, 2, 12007, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;

-- Children of: babies-kids
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Baby Clothing', 'baby-clothing', 'babies-kids/baby-clothing', 1, '576f1bcc-12c3-4f06-8d55-4e2471b3d158', '🍼', true, 2, 13000, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Prams & Strollers', 'prams-strollers', 'babies-kids/prams-strollers', 1, '576f1bcc-12c3-4f06-8d55-4e2471b3d158', '🛒', true, 2, 13001, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Baby Gear & Furniture', 'baby-gear', 'babies-kids/baby-gear', 1, '576f1bcc-12c3-4f06-8d55-4e2471b3d158', '🛏️', true, 2, 13002, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Toys', 'toys', 'babies-kids/toys', 1, '576f1bcc-12c3-4f06-8d55-4e2471b3d158', '🧸', true, 2, 13003, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('School Supplies', 'school-supplies', 'babies-kids/school-supplies', 1, '576f1bcc-12c3-4f06-8d55-4e2471b3d158', '🎒', true, 2, 13004, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;

-- Children of: food-agriculture
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Fresh Produce', 'fresh-produce', 'food-agriculture/fresh-produce', 1, 'dc5521eb-7135-47c4-aaab-0ec90ef46026', '🥦', true, 2, 14000, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Farm Animals & Livestock', 'livestock', 'food-agriculture/livestock', 1, 'dc5521eb-7135-47c4-aaab-0ec90ef46026', '🐄', true, 2, 14001, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Seeds & Seedlings', 'seeds-seedlings', 'food-agriculture/seeds-seedlings', 1, 'dc5521eb-7135-47c4-aaab-0ec90ef46026', '🌱', true, 2, 14002, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Farm Inputs & Fertilizers', 'farm-inputs', 'food-agriculture/farm-inputs', 1, 'dc5521eb-7135-47c4-aaab-0ec90ef46026', '🧪', true, 2, 14003, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Irrigation & Farming Equipment', 'irrigation-equipment', 'food-agriculture/irrigation-equipment', 1, 'dc5521eb-7135-47c4-aaab-0ec90ef46026', '💧', true, 2, 14004, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;

-- Children of: animals-pets
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Dogs', 'dogs', 'animals-pets/dogs', 1, '80645f93-1ed7-4344-8ef3-2a4830f2d203', '🐕', true, 2, 15000, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Cats', 'cats', 'animals-pets/cats', 1, '80645f93-1ed7-4344-8ef3-2a4830f2d203', '🐈', true, 2, 15001, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Birds', 'birds', 'animals-pets/birds', 1, '80645f93-1ed7-4344-8ef3-2a4830f2d203', '🦜', true, 2, 15002, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Fish & Aquariums', 'fish-aquariums', 'animals-pets/fish-aquariums', 1, '80645f93-1ed7-4344-8ef3-2a4830f2d203', '🐟', true, 2, 15003, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Pet Supplies & Accessories', 'pet-supplies', 'animals-pets/pet-supplies', 1, '80645f93-1ed7-4344-8ef3-2a4830f2d203', '🦴', true, 2, 15004, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;

-- Children of: auto-spares
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Engine Components', 'engine-components', 'auto-spares/engine-components', 1, '88bda9e6-01c9-493e-86ec-f770df6bdac5', '🔩', true, 2, 16000, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Brakes & Suspension', 'brakes-suspension', 'auto-spares/brakes-suspension', 1, '88bda9e6-01c9-493e-86ec-f770df6bdac5', '🔧', true, 2, 16001, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Body & Exterior', 'body-exterior', 'auto-spares/body-exterior', 1, '88bda9e6-01c9-493e-86ec-f770df6bdac5', '🚘', true, 2, 16002, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Electrical & Lighting', 'auto-electrical', 'auto-spares/auto-electrical', 1, '88bda9e6-01c9-493e-86ec-f770df6bdac5', '💡', true, 2, 16003, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Transmission & Drivetrain', 'transmission', 'auto-spares/transmission', 1, '88bda9e6-01c9-493e-86ec-f770df6bdac5', '⚙️', true, 2, 16004, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Tyres & Wheels', 'tyres-wheels', 'auto-spares/tyres-wheels', 1, '88bda9e6-01c9-493e-86ec-f770df6bdac5', '🛞', true, 2, 16005, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Car Audio & Accessories', 'car-audio', 'auto-spares/car-audio', 1, '88bda9e6-01c9-493e-86ec-f770df6bdac5', '🔊', true, 2, 16006, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Oil, Fluids & Filters', 'oils-fluids', 'auto-spares/oils-fluids', 1, '88bda9e6-01c9-493e-86ec-f770df6bdac5', '🛢️', true, 2, 16007, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Tools & Garage Equipment', 'garage-tools', 'auto-spares/garage-tools', 1, '88bda9e6-01c9-493e-86ec-f770df6bdac5', '🔨', true, 2, 16008, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;

-- Children of: jobs
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Accounting & Finance', 'accounting-finance', 'jobs/accounting-finance', 1, 'dc6cfe64-02cf-4116-a605-6a3742c091f7', '💰', true, 2, 17000, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Admin & Secretarial', 'admin-secretarial', 'jobs/admin-secretarial', 1, 'dc6cfe64-02cf-4116-a605-6a3742c091f7', '📋', true, 2, 17001, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Agriculture & Farming', 'agri-jobs', 'jobs/agri-jobs', 1, 'dc6cfe64-02cf-4116-a605-6a3742c091f7', '🌾', true, 2, 17002, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Construction & Engineering', 'construction-jobs', 'jobs/construction-jobs', 1, 'dc6cfe64-02cf-4116-a605-6a3742c091f7', '🏗️', true, 2, 17003, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Customer Service & Sales', 'customer-service', 'jobs/customer-service', 1, 'dc6cfe64-02cf-4116-a605-6a3742c091f7', '🤝', true, 2, 17004, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Driving & Transport', 'driving-jobs', 'jobs/driving-jobs', 1, 'dc6cfe64-02cf-4116-a605-6a3742c091f7', '🚕', true, 2, 17005, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Education & Training', 'education-jobs', 'jobs/education-jobs', 1, 'dc6cfe64-02cf-4116-a605-6a3742c091f7', '🎓', true, 2, 17006, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Healthcare & Medical', 'healthcare-jobs', 'jobs/healthcare-jobs', 1, 'dc6cfe64-02cf-4116-a605-6a3742c091f7', '🏥', true, 2, 17007, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Hospitality & Tourism', 'hospitality-jobs', 'jobs/hospitality-jobs', 1, 'dc6cfe64-02cf-4116-a605-6a3742c091f7', '🏨', true, 2, 17008, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('ICT & Tech', 'ict-jobs', 'jobs/ict-jobs', 1, 'dc6cfe64-02cf-4116-a605-6a3742c091f7', '💻', true, 2, 17009, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Legal', 'legal-jobs', 'jobs/legal-jobs', 1, 'dc6cfe64-02cf-4116-a605-6a3742c091f7', '⚖️', true, 2, 17010, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Media & Creative', 'media-jobs', 'jobs/media-jobs', 1, 'dc6cfe64-02cf-4116-a605-6a3742c091f7', '🎬', true, 2, 17011, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Security & Guarding', 'security-jobs', 'jobs/security-jobs', 1, 'dc6cfe64-02cf-4116-a605-6a3742c091f7', '🛡️', true, 2, 17012, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;

-- Children of: seeking-work
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Drivers & Chauffeurs', 'seeking-driver', 'seeking-work/seeking-driver', 1, 'c0786cdf-26d5-4b9d-95b6-4e3af26c6bf1', '🚗', true, 2, 18000, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Domestic Workers', 'seeking-domestic', 'seeking-work/seeking-domestic', 1, 'c0786cdf-26d5-4b9d-95b6-4e3af26c6bf1', '🏠', true, 2, 18001, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('IT & Tech Professionals', 'seeking-ict', 'seeking-work/seeking-ict', 1, 'c0786cdf-26d5-4b9d-95b6-4e3af26c6bf1', '💻', true, 2, 18002, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Engineers & Technicians', 'seeking-engineer', 'seeking-work/seeking-engineer', 1, 'c0786cdf-26d5-4b9d-95b6-4e3af26c6bf1', '🔧', true, 2, 18003, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Teachers & Tutors', 'seeking-teacher', 'seeking-work/seeking-teacher', 1, 'c0786cdf-26d5-4b9d-95b6-4e3af26c6bf1', '📚', true, 2, 18004, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;
INSERT INTO categories (name, slug, path, depth, parent_id, icon, is_active, level, order_index, allow_condition, allow_location, allow_negotiable, allow_price, allow_video, allow_pdf, allow_360, min_photos, max_photos, listing_fee) VALUES ('Healthcare Workers', 'seeking-healthcare', 'seeking-work/seeking-healthcare', 1, 'c0786cdf-26d5-4b9d-95b6-4e3af26c6bf1', '🩺', true, 2, 18005, true, true, true, true, false, false, false, 1, 10, 0) ON CONFLICT (path) DO NOTHING;

SET session_replication_role = 'origin';

-- Verify
SELECT COUNT(*) AS total_categories, COUNT(parent_id) AS child_categories FROM categories;