const COUNTY_TOWNS = {
  'Nairobi': ['CBD', 'Westlands', 'Kasarani', 'Embakasi', 'Langata', 'Karen', 'Kilimani', 'Upperhill', 'South B', 'South C', 'Eastleigh', 'Parklands', 'Industrial Area', 'Githurai', 'Roysambu', 'Ruaraka', 'Dagoretti', 'Kabete', 'Runda', 'Gigiri', 'Spring Valley', 'Lavington', 'Hurlingham', 'Kileleshwa', 'Buruburu', 'Donholm', 'Umoja', 'Kayole', 'Komarock', 'Njiru'],
  'Mombasa': ['Mombasa Island', 'Nyali', 'Bamburi', 'Kisauni', 'Likoni', 'Changamwe', 'Jomvu', 'Mikindani', 'Miritini', 'Port Reitz', 'Mtongwe', 'Shimanzi'],
  'Kwale': ['Kwale Town', 'Ukunda', 'Diani Beach', 'Msambweni', 'Lungalunga', 'Kinango', 'Shimba Hills', 'Vanga', 'Mwabungo', 'Ramisi'],
  'Kilifi': ['Kilifi Town', 'Malindi', 'Watamu', 'Mtwapa', 'Kaloleni', 'Rabai', 'Ganze', 'Mariakani', 'Sokoke', 'Takaungu'],
  'Tana River': ['Hola', 'Garsen', 'Bura', 'Madogo', 'Wema', 'Kipini', 'Galole'],
  'Lamu': ['Lamu Town', 'Mpeketoni', 'Witu', 'Hindi', 'Faza', 'Mokowe', 'Kiunga', 'Shella', 'Matondoni'],
  'Taita-Taveta': ['Voi', 'Wundanyi', 'Taveta', 'Mwatate', 'Moshi', 'Mkwaju', 'Bura', 'Kaloleni'],
  'Garissa': ['Garissa Town', 'Dadaab', 'Bura', 'Hulugho', 'Masalani', 'Ijara', 'Fafi', 'Balambala'],
  'Wajir': ['Wajir Town', 'Habaswein', 'Elwak', 'Bute', 'Griftu', 'Tarbaj', 'Wajir South', 'Eldas'],
  'Mandera': ['Mandera Town', 'Takaba', 'Rhamu', 'Lafey', 'Banissa', 'Arabia', 'Kutulo'],
  'Marsabit': ['Marsabit Town', 'Moyale', 'Laisamis', 'North Horr', 'Loiyangalani', 'Sololo', 'Saku', 'Turbi'],
  'Isiolo': ['Isiolo Town', 'Merti', 'Garbatulla', 'Kula Mawe', 'Modogashe', 'Oldonyiro'],
  'Meru': ['Meru Town', 'Nkubu', 'Maua', 'Laare', 'Timau', 'Mwimbi', 'Githongo', 'Mikinduri', 'Igoji', 'Kianjai'],
  'Tharaka-Nithi': ['Chuka', 'Marimanti', 'Gatunga', 'Kathwana', 'Kibirichia', 'Muthambi'],
  'Embu': ['Embu Town', 'Runyenjes', 'Ena', 'Ishiara', 'Siakago', 'Manyatta', 'Kiritiri', 'Gachoka'],
  'Kitui': ['Kitui Town', 'Mwingi', 'Mutomo', 'Kyuso', 'Zombe', 'Tseikuru', 'Katulani', 'Ikanga', 'Nuu', 'Migwani'],
  'Machakos': ['Machakos Town', 'Athi River', 'Mlolongo', 'Mavoko', 'Katani', 'Tala', 'Kangundo', 'Matuu', 'Masii', 'Kathiani', 'Mwala', 'Yatta', 'Mutituni'],
  'Makueni': ['Wote', 'Makindu', 'Sultan Hamud', 'Emali', 'Kibwezi', 'Mtito Andei', 'Nunguni', 'Kathonzweni', 'Kilome'],
  'Nyandarua': ['Ol Kalou', 'Engineer', 'Ndaragwa', 'Kinangop', 'Mirangine', 'Nyahururu', 'Njabini', 'Kaimbaga'],
  'Nyeri': ['Nyeri Town', 'Karatina', 'Othaya', 'Mukurweini', 'Tetu', 'Kingori', 'Mathira', 'Mweiga', 'Narumoru'],
  'Kirinyaga': ['Kerugoya', 'Kutus', 'Sagana', 'Kagio', 'Wanguru', 'Baricho', 'Mwea', 'Kianyaga'],
  "Murang'a": ["Murang'a Town", 'Thika', 'Kangema', 'Maragua', 'Kandara', 'Gatanga', 'Kigumo', 'Kiharu', 'Kenol', 'Makuyu'],
  'Kiambu': ['Kiambu Town', 'Thika', 'Ruiru', 'Kikuyu', 'Limuru', 'Githunguri', 'Kabete', 'Gatundu', 'Juja', 'Karuri', 'Kasarani', 'Tigoni', 'Banana'],
  'Turkana': ['Lodwar', 'Kakuma', 'Lokichogio', 'Kalokol', 'Lokichar', 'Loima', 'Kainuk', 'Todonyang'],
  'West Pokot': ['Kapenguria', 'Sigor', 'Alale', 'Lomut', 'Makutano', 'Lelan', 'Kacheliba', 'Chepareria'],
  'Samburu': ['Maralal', 'Wamba', "Archer's Post", 'Baragoi', 'Suguta Marmar', 'Kisima', 'Nyahururu'],
  'Trans Nzoia': ['Kitale', 'Endebess', 'Saboti', 'Kwanza', 'Kiminini', 'Bidii', 'Cherangany'],
  'Uasin Gishu': ['Eldoret', 'Turbo', 'Moiben', 'Kapseret', 'Langas', 'Burnt Forest', 'Ziwa'],
  'Elgeyo-Marakwet': ['Iten', 'Kapsowar', 'Chesongoch', 'Soy North', 'Tambach', 'Keiyo'],
  'Nandi': ['Kapsabet', 'Nandi Hills', 'Mosoriot', 'Lessos', 'Chepterwai', 'Aldai', 'Kobujoi', 'Nandi South'],
  'Baringo': ['Kabarnet', 'Eldama Ravine', 'Marigat', 'Mogotio', 'Timboroa', 'Iten', 'Tenges', 'Nginyang'],
  'Laikipia': ['Nanyuki', 'Rumuruti', 'Nyahururu', 'Doldol', 'Ol Moran', 'Kinamba', 'Laikipia North'],
  'Nakuru': ['Nakuru Town', 'Naivasha', 'Gilgil', 'Molo', 'Njoro', 'Rongai', 'Subukia', 'Bahati', 'Mbaruk', 'Hells Gate', 'Salgaa'],
  'Narok': ['Narok Town', 'Kilgoris', 'Ololulunga', 'Suswa', 'Ntulele', 'Melelo', 'Sekenani', 'Lemek'],
  'Kajiado': ['Kajiado Town', 'Ongata Rongai', 'Kitengela', 'Ngong', 'Kiserian', 'Namanga', 'Loitokitok', 'Mashuru', 'Isinya', 'Bissil'],
  'Kericho': ['Kericho Town', 'Litein', 'Londiani', 'Kipkelion', 'Belgut', 'Sosiot', 'Fort Ternan', 'Soin'],
  'Bomet': ['Bomet Town', 'Sotik', 'Longisa', 'Chemaner', 'Ndanai', 'Mulot', 'Merigi', 'Sigor'],
  'Kakamega': ['Kakamega Town', 'Mumias', 'Malava', 'Butere', 'Lugari', 'Navakholo', 'Khwisero', 'Likuyani', 'Matungu', 'Lurambi'],
  'Vihiga': ['Vihiga Town', 'Mbale', 'Luanda', 'Hamisi', 'Sabatia', 'Chavakali', 'Mudete'],
  'Bungoma': ['Bungoma Town', 'Webuye', 'Kimilili', 'Chwele', 'Sirisia', 'Malakisi', 'Mt Elgon', 'Tongaren', 'Bumula'],
  'Busia': ['Busia Town', 'Malaba', 'Nambale', 'Port Victoria', 'Butula', 'Funyula', 'Amagoro', 'Nambale'],
  'Siaya': ['Siaya Town', 'Bondo', 'Ugunja', 'Ndori', 'Ukwala', 'Yala', 'Rarieda', 'Ambira', 'Karemo'],
  'Kisumu': ['Kisumu Town', 'Ahero', 'Maseno', 'Muhoroni', 'Nyando', 'Katito', 'Nyamasaria', 'Kombewa', 'Mamboleo'],
  'Homa Bay': ['Homa Bay Town', 'Oyugis', 'Kendu Bay', 'Ndhiwa', 'Mbita', 'Rangwe', 'Rongo', 'Karungu', 'Sindo'],
  'Migori': ['Migori Town', 'Awendo', 'Uriri', 'Isebania', 'Kehancha', 'Ntimaru', 'Rongo', 'Macalder'],
  'Kisii': ['Kisii Town', 'Ogembo', 'Suneka', 'Marani', 'Nyamache', 'Masimba', 'Ichuni', 'Riosiri', 'Keroka'],
  'Nyamira': ['Nyamira Town', 'Manga', 'Ekerenyo', 'Keroka', 'Nyansiongo', 'Masaba', 'Magombo', 'Rigoma'],
};

export const COUNTIES = Object.keys(COUNTY_TOWNS).sort();
export const getTowns = (county) => COUNTY_TOWNS[county] || [];
export default COUNTY_TOWNS;
